apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configs
data:
    {{- (.Files.Glob "event_status.template.json").AsConfig | nindent 2 }}
    {{- (.Files.Glob "job_status.template.json").AsConfig | nindent 2 }}
    {{- (.Files.Glob "logstash.conf").AsConfig | nindent 2 }}
    {{- (.Files.Glob "logstash.yml").AsConfig | nindent 2 }}
    {{- (.Files.Glob "task_status.template.json").AsConfig | nindent 2 }}
    {{- (.Files.Glob "worker_status.template.json").AsConfig | nindent 2 }}